import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { background, Box } from '@chakra-ui/react'

// Components chakra UI



// Components react



// Project components
import ProfilePicture from '../components/profile/profilepicture'
import BasicInfo from '../components/profile/basicinfo'
import MainContent from '../components/maincontent/main'

export default function Home() {
  // document.body.setAttribute('style', 'background: #202828;')
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {/* <ProfilePicture username="LyeZinho" /> */}
      <Box p={2}>
        <MainContent />
      </Box>
    </div>
  )
}
