import Head from 'next/head'
import Image from 'next/image'
import Document, { Html, Main } from 'next/document'


// Components chakra UI
import { background, Box, Heading } from '@chakra-ui/react'
import { Link } from '@chakra-ui/react'

// Components react



// Project components
import ProfilePicture from '../components/profile/profilepicture'
import BasicInfo from '../components/profile/basicinfo'
import MainContent from '../components/maincontent/main'


//Palette
//https://coolors.co/palette/181818-151514-202828-1cae8e-03fbcb
export default function Home() {
  return (
    <div
      style={{
        backgroundColor: '#202828',
        width: '100%',
        height: '100%'
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <ProfilePicture username="LyeZinho" /> */}
      <Box p={2}>
        <MainContent />
      </Box>
    </div>
  )
}
